### PR TITLE
feat: ✨ sd-button with sd-badge sample

### LINKED ISSUE #341: feat: ✨ Add sample for sd-button with sd-badge
## Description
Add a sample (story) for showing sd-badge attached to sd-button.

## Hand-off
[LINK TO FIGMA](https://www.figma.com/file/frKFVz9UBKAtsvErLKTeGj/Badge?node-id=1613%3A125&mode=dev)

## DoR
- [ ] Item has business value
- [ ] Item has been estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by Vahid1919**
## Description:
Added a samples story to showcase the sd-button working with sd-badge. Closes #341 

## Definition of Reviewable:
*PR notes: Irrelevant elements should be removed.*
- [x] Documentation is created/updated
- [x] Stories (features, a11y) are created/updated
- [x] relevant tickets are linked
- [x] PR is assigned to project board

### CODE REVIEW

**Review by MarcMatthiae — COMMENTED** [review]
@coraliefeil Correct me if I´m wrong, but as I remember it, the badge is supposed to "grow to the left" when the texts gets longer.

@Vahid1919 That is the exact point I got stuck the last time, as you have to change the positioning of the badge in the button component.

image

**Comment by coraliefeil** [comment]
Yes growing to the left would be good ... if possible in code ... if that is causing too much stress, centered would be ok as well. only to the right growing would look weird I guess.

**Comment by mariohamann** [comment]
@Vahid1919 What is the current state of this ticket?

**Comment by Vahid1919** [comment]
> @Vahid1919 What is the current state of this ticket?

@mariohamann I have to look into the growing behavior to see what I can do. Currently it is growing to the right which is not the behaviour we want.

**Comment by coraliefeil** [comment]
Well, if it is growing from it’s center then that’s ok ...

**Comment by Vahid1919** [comment]
@coraliefeil Requesting re-review after a fix for the tertiary buttons :)
I also reworked the sample to closely resemble the Figma document.

**Review by karlbaumhauer — APPROVED** [review]

**Comment by Vahid1919** [comment]
@van-nguyen-ht Assigning this to you for the Chromatic tests/review :)

**Comment by abudd1094** [comment]
@Vahid1919 @mariohamann 
The problem is the "translate: 50% -50%" on the badge slot in the button.  This can be fixed by using absolute positioning to do the desired translate, then the badge will grow to the left:
image

**Comment by Vahid1919** [comment]
@van-nguyen-ht I aligned a small margin difference I noticed between the inverted and non-inverted tertiary buttons. Please review :)

**Pull request merged**
