### PR TITLE
chore: 🔧 update issue templates

### PR DESCRIPTION
**Pull request by karlbaumhauer**
- updated standard issue template
- added epic issue template

### CODE REVIEW

**Comment by karlbaumhauer** [comment]
@mariohamann do we need another one for now?

**Comment by karlbaumhauer** [comment]
@mariohamann I added some more issue types I found in our current backlog

**Comment by karlbaumhauer** [comment]
> IMO all the DOR and DOD stuff is way to oversized. I would propose to remove them for now and really think about what could be part of the ticket which really helps
> 
> * DOD: In the moment as most stuff doesn't fit to every task or sometimes is too component focused etc. Maybe we have to generalize some stuff or have to move it into the PR or I don't know..
> * DOR: At least the DOR shouldn't be part of the ticket but more something we have on the side when we refine tickets.
> 
> Maybe we could discuss in the orga meeting or in a refinement.

as you mentioned last time that the refinement feels strange and you questioned the need, I realized that with the DOR and DOD we would be able have a clearer goal for the refinement IMO.

In addition to this, I would like to keep it for the following two reasons:
1. we agreed to have them but never really tried to use them
2. reading tickets for me is hard as they are too different in terms of content

both point would make reading and organizing tickets easier for me.

**Comment by mariohamann** [comment]
Then just let it reduce, because I have the feeling that the important stuff is overwhelmed by redundant stuff:
```
## DoR
- [ ] ❌ Item has business value → If not, it sholdn't exist and we should just close it.
- [ ] ✏️Item is estimated by the team
- [ ] ✏️ Item is clear and well-defined
- [ ] ❌ Item is achievable within a sprint → We don't have sprints
- [ ] ❓ Item is measurable and testable upon completion (Acceptance Criteria) → I don't know how to value that.
- [ ] Item dependencies have been identified

## DoD
- [ ] ❌ Changes have been pushed and reviewed → This is like: You wrote code. Or you did something. Feels redundant.
- [ ] ✏️Documentation has been created/updated (if applicable)
- [ ] ✏️Migration Guide has been created/updated (if applicable)
- [ ] ➕ Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] ➕ Relevant stories (Features, A11y) are created/updated
- [ ] ❌ Implementation works successfully on `feature` branch → This is part of the review or the whole point of an ticket?
- [ ] ❌ Automatic tests have passed on `feature` branch → This is done by Quality Gate. Nothing that someone manually has to check.
- [ ] ❌ Accessibility has been approved on `feature` branch → I have no idea when this could be checked. 
- [ ] ❌ Changes have been merged (`feature` branch has been deleted) → This can't be tested in a PR.
- [ ] ❌ Automatic tests have passed on `main` branch → This can't be tested in a PR. As Actions on GitHub merge the main branch, this happens automatically.
- [ ] ❌ Accessibility has been approved on `main` branch → This can't be tested in a PR. → This can't be tested in a PR. As Actions on GitHub merge the main branch, this happens automatically.
```

So my suggestion would be:
```
## DoR
- [ ] Item has business value
- [ ] Item is estimated by the team
- [ ] Item is clear and well-defined
- [ ] Item dependencies are identified

## DoD
*Irrelevant elements should be removed in refinement.*
- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
```

This would help me a lot more on focusing what to do.

**Comment by mariohamann** [comment]
On top I would suggest to create a Pull Request Template with the DoD: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template

**Comment by karlbaumhauer** [comment]
> On top I would suggest to create a Pull Request Template with the DoD: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template

@mariohamann I thought about that but wasn't sure if it is really needed... especially the DoD in the PR has to be checked after you merged the PR and therewith closed it...

I think the question where to start and where to end the job of a DoR or DoD needs to be discussed.

as I suggested something and you wrote your thoughts on that, I would like to clarify in the team what everybody needs... I think the most obvious points sometimes need to be written down... ;-)

**Comment by karlbaumhauer** [comment]
@mariohamann I updated DoR and DoD with your suggestions (partly).
As we cant use the templates until they are merged on main, I would love to merge it and see in the next weeks how they might improve our issue management and refactor them in a second step if necessary (and/or after we managed to align in the team next weekly).

**Review by mariohamann — APPROVED** [review]

**Pull request merged**
