### PR TITLE
docs: add v4 announcement page and hint on introduction page [skip chromatic]

### LINKED ISSUE #1366: docs: 📚 add Storybook restructure information to introduction page
## Description
In order to promote and explain our latest changes with the docs in Storybook, a more detailed "release notes" should be added to Storybook.
Therefore a new page under `docs/general/*` should be created and the "introduction" page should have a short description and link to the respective page.
## Where to put the documentation
Storybook
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [x] Documentation has been created/updated (if applicable)
- [x] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by karlbaumhauer**
## Description:
Adds announcement to version 4 
- adds additional announcement page to general docs
- adds link to announcement page to start of introduction page

closes #1366 and https://github.com/solid-design-system/internal/issues/84

## Definition of Reviewable:
- [x] Documentation is created/updated
- [x] relevant tickets are linked

### CODE REVIEW

**Review by smfonseca — APPROVED** [review]

**Comment by coraliefeil** [comment]
Is this part still in there? Needs to be updated since we now name all of these things templates.

Bildschirmfoto 2024-09-12 um 09 05 25

**Comment by coraliefeil** [comment]
Let’s delete the emojis ... brand does not allow them

**Comment by karlbaumhauer** [comment]
> Let’s delete the emojis ... brand does not allow them

removed them... :-(

**Comment by karlbaumhauer** [comment]
> Is this part still in there? Needs to be updated since we now name all of these things templates.
> 
> Bildschirmfoto 2024-09-12 um 09 05 25

yes. IMO this is part of the change in general. We need to refactor our whole documentation and look for infos we need to adopt. 

=> I will create a ticket for that.

**Review by yoezlem — APPROVED** [review]

**Comment by karlbaumhauer** [comment]
@coraliefeil I just added one part to the changes as the rest is more or less just different or more text on the same place.

@auroraVasconcelos & @MartaPintoTeixeira pls have a look into it and let me know if you found anything, we missed to announce.

**Comment by mariohamann** [comment]
The docs branch shouldn't contain breaking changes. This would lead to problems on `npm i` or updating, as in regard to semver there are changes implied, that aren't existing. Not sure, why this is needed?

**Review by mariohamann — CHANGES_REQUESTED** [review]
Let's clarify need for this branch first.

**Comment by smfonseca** [comment]
After discussing the content of this PR together with @yoezlem and @mariohamann, we were not sure if this was the best way to announce the docs rewrite. We came up with a different approach, therefore I'm closing this PR.

**Pull request closed without merging**
