### PR TITLE
docs: 📚 housekeeping – align slots

### LINKED ISSUE #359: docs: 📚 housekeeping – align slots
## Description

We have different implementations of the slot and my initial thing was some kind of pseudo-custom-element css vars etc.

It's interface it NOT good and starting it's starting to get a bit messy:

CleanShot 2023-08-30 at 14 44 38@2x
CleanShot 2023-08-30 at 14 44 51@2x
CleanShot 2023-08-30 at 14 45 05@2x
CleanShot 2023-08-30 at 14 46 05@2x

For the `sd-dropdown` I implemented more dynamic BEM-CSS-classes, which you can use to just set an outline, set a background and optionally write content or whatever.

CleanShot 2023-08-30 at 14 45 28@2x

## Summary
- only use the classes used in `sd-dropdown` story
- remove `slot-comp` classes

## Where to put the documentation
- [x] update all related stories
- [ ] add to contribution guide (classes are part of the storybook head => **_ONLY_** to be used in storybook)

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by Vahid1919**
## Description:
Replaces all instances of slot-comp in our repository and added a bullet point explaining usage of slots . Closes #359

## Definition of Reviewable:
*PR notes: Irrelevant elements should be removed.*
- [x] Documentation is created/updated
- [x] Stories (features, a11y) are created/updated
- [x] relevant tickets are linked
- [x] PR is assigned to project board

### CODE REVIEW

**Review by yoezlem — APPROVED** [review]

**Comment by mariohamann** [comment]
Please fix this one, too:

https://64469bd84c5ea1ce2dd5d016-mtihaktguv.chromatic.com/?path=/story/components-sd-badge--slots

**Comment by mariohamann** [comment]
CleanShot 2023-10-04 at 14 18 38@2x

Copy Paste errors here.


In general: I think it makes sense to always write the slot name isntead of this `repalce this slot` thing everywhere.

**Comment by Vahid1919** [comment]
> CleanShot 2023-10-04 at 14 18 38@2x
> Copy Paste errors here.
> 
> In general: I think it makes sense to always write the slot name isntead of this `repalce this slot` thing everywhere.

@mariohamann I addressed these in the latest commit. 

Regarding how we approach them in general, should this be a bigger conversation with the team since Design also uses the "Replace this slot" in most components?

**Comment by Vahid1919** [comment]
@van-nguyen-ht Updated the slot component on all the components that used it. Assigning for Review :)

**Comment by mariohamann** [comment]
> > Copy Paste errors here.
> > In general: I think it makes sense to always write the slot name isntead of this `repalce this slot` thing everywhere.
> 
> @mariohamann I addressed these in the latest commit.
> 
> Regarding how we approach them in general, should this be a bigger conversation with the team since Design also uses the "Replace this slot" in most components?

Yeah, makes sense. Personally I would like to have a clean state at least in development and then we could have a look, if design could catch up. What do you think?

**Pull request merged**
