### PR TITLE
docs: update link template docs [skip chromatic]

### PR DESCRIPTION
**Pull request by auroraVasconcelos**
## Description:
Closes https://github.com/solid-design-system/solid/issues/1445

## Definition of Reviewable:

- [x] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated

- [x] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

### CODE REVIEW

**Review by karlbaumhauer — APPROVED** [review]

**Comment by MartaPintoTeixeira** [comment]
Can you make the anchor link list bold as in figma please?

**Comment by MartaPintoTeixeira** [comment]
Instead of: Link with Icon
Change it to: Link 

For the moment I would only use with if we are mentioning a style or component to combine with the component in the template.

**Comment by auroraVasconcelos** [comment]
> Can you make the anchor link list bold as in figma please?

Updated

**Comment by MartaPintoTeixeira** [comment]
On the last sample instead of:
Protecting is out priority
Should be:
Protecting is our priority

**Review by MartaPintoTeixeira — APPROVED** [review]

**Pull request merged**
