### PR TITLE
fix: sd-carousel & sd-carousel-item a11y

### LINKED ISSUE #1470: feat[dev]: ✨ implement A11y improvements to sd-carousel & sd-carousel-item
## Description
This task describes the Storybook implementation for the sd-brandshape component as part of the A11y improvements outlined in Epic https://github.com/solid-design-system/solid/issues/1465.

A11y improvements for sd-sd-carousel and sd-carousel-item can be found here: [sd-carousel Notes](https://www.notion.so/matuzo/sd-carousel-sd-carousel-item-105f3f6e1bc080c3af6cf953f669bb88).

----------------------------------------

## Comment
**Problem:** There’s no announcement when slides change because #scroll-container is not a live region. aria-atomic and aria-busy alone do not affect the #scroll-container. It must be a live region.
**Solution:** Add aria-live=polite|assertive to the #scroll-container or use role=status|alert instead.

**Problem:** #scroll-container is a generic element (div) but is focusable. If you add tabindex=0 to an element, it must also have an accessible name and a non-generic role.
**Solution:** Use role=status instead of aria-atomic=true. It’s a shorthand for aria-live=polite and aria-atomic=true. It gives you the setting you want and a semantic role.

**Problem:** Manually turning #scroll-container into a live region, you get an announcement, but it’s broken. You get something like “Previous slide NaN / 3 Next slide [alt]”.
**Solution:** When you add the role also fix and simplify the announcement, e.g. “[alt] 2 of 3”.

**Problem:** The play/pause button doesn't indicate whether the carousel is currently playing.
**Solution:** By default, set aria-pressed="true" and toggle the value when the button is activated. Tigh this to the function which stops or plays the carousel.

**Problem:** The play/pause button has no accessible name.
**Solution:** Add one.

**Problem:** Focus is lost on the previous/next buttons when you reach the first/last slide because the buttons turn into the disabled state.
**Solution:** Move focus to the other active button or change your solution for disabled buttons (see [@sd-button](https://www.notion.so/matuzo/sd-button-104f3f6e1bc0800b9f72d2a046316ec3)).

## Notes
- There are options to change the previous and next icons, but is it also possible to change the accessible names, e.g., provided by aria-label? The would be important for i18n.
- As the role / accessible name should not be changed but the icons need to be flexible (skinning), we should only make this clear in the documentation.

## Best Practices
Carousels are generally hard for screen reader users to use; try to avoid it.

## Related WCAG criteria
- https://www.w3.org/WAI/WCAG22/quickref/#name-role-value
- https://www.w3.org/WAI/WCAG22/quickref/#status-messages

## Additional resources
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

### Open Questions
- [ ] Question1
- [ ] Question2

## DoR
- [x] Item has been estimated by the team
- [x] Item dependencies have been identified and documented

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by Vahid1919**
## Description:

closes #1470

## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated

- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

### CODE REVIEW

**Comment by Vahid1919** [comment]
@MartaPintoTeixeira @coraliefeil Please take a look at the Autoplay story for the sd-carousel docs. I have updated the documentation (code only) to explain why the autoplay is paused by default.

**Review by karlbaumhauer — DISMISSED** [review]

**Comment by MartaPintoTeixeira** [comment]
On the Variants can we use small letters for: "Number" and "Dot"?
To keep consistency across the docs.

**Comment by MartaPintoTeixeira** [comment]
Figma docs updated accordingly for the section "Autoplay". FYI @coraliefeil and @Vahid1919

**Comment by MartaPintoTeixeira** [comment]
Screenshot 2024-10-31 at 10 23 09
Autoplay should have slot 1 by default.

**Comment by MartaPintoTeixeira** [comment]
Question: Should the autoplay be paused as well in the template?

**Review by mariohamann — DISMISSED** [review]
Looks lovely from code perspective.

**Comment by Vahid1919** [comment]
> @Vahid1919 I tested the carousel with voice over on chrome and I could not get announcements for the carousel slides content, status of the autoplay button (it says it's selected but when it's deselected there is no information) and there's also no information when you use the keyboard the go to the next or previous slide.
> 
> Or safari the slides content is announced when moving between slides. The autoplay is also only announced as selected, no information when it's deselected.

Created a follow up ticket to discuss inconsistencies in slide announcements: #1653

**Review by smfonseca — DISMISSED** [review]

**Review by MartaPintoTeixeira — CHANGES_REQUESTED** [review]
for the variant section let's have 1st number and then dots in the sample to match the copy

**Comment by MartaPintoTeixeira** [comment]
on the slides per move section figma sample is different. can this be updated in this ticket?

**Comment by MartaPintoTeixeira** [comment]
in the template the "loop with autoplay" section is starting in image 3
should start in image 1.

also this samples is not working well: when i click the 3rd time in the right arrow it jumps 2 images instead of 1

**Comment by MartaPintoTeixeira** [comment]
for the disabled section the content inside the textarea should be neutral-500 and is neutral-700.
let me know if this is an issue in the component. if so please open a ticket to fix it and align with figma.

**Comment by MartaPintoTeixeira** [comment]
As spoken my feedback is:
- the samples Variant sections are broken - should be side by side starting with number
- on the templates the loop is displaying image 3 as a start - should be image 1
- on the templates the loop is behavind weired (if i keep clicking in the right arrow sometimes jumps from image 3 to image 2 - should jump to image 1 in that case)

**Review by MartaPintoTeixeira — APPROVED** [review]

**Comment by MartaPintoTeixeira** [comment]
Approved this PR but created a new ticket to solve the issues on the loop video sample (in templates) [#1666](https://github.com/solid-design-system/solid/issues/1666)

**Review by paulovareiro29 — CHANGES_REQUESTED** [review]
@Vahid1919 I have tested using a screenreader and when changing slides I would expect some announcement stating in which slide I am. This kind of announcement currently only happens when you refocus the slide.

Here are the expected behaviors from my side on a slide:
- when slide content is focused and I use the arrows to change slide, it should announce "Slide x / y"
- when prev/next button is focused and I press it, it should announce "Slide x / y"

**Comment by Vahid1919** [comment]
> @Vahid1919 I have tested using a screenreader and when changing slides I would expect some announcement stating in which slide I am. This kind of announcement currently only happens when you refocus the slide.
> 
> Here are the expected behaviors from my side on a slide:
> 
> * when slide content is focused and I use the arrows to change slide, it should announce "Currently on slide x / y"
> * when prev/next button is focused and I press it, it should announce "Currently on slide x / y"

@paulovareiro29 Which browser did you test this on? It might be a similar issue as mentioned by @smfonseca on the previous thread: https://github.com/solid-design-system/solid/pull/1607#issuecomment-2478837057

**Comment by paulovareiro29** [comment]
@Vahid1919 sorry about that... the comment was hidden 🤦

**Review by paulovareiro29 — APPROVED** [review]

**Review by auroraVasconcelos — APPROVED** [review]

**Review by smfonseca — APPROVED** [review]

**Pull request merged**
