### PR TITLE
fix: 🤔 sd-textarea doesn't accept full height of container

### LINKED ISSUE #719: fix: 🤔 sd-textarea doesn't accept full height of container
## Current behavior
if you place a sd-textarea with height:100% in a container the sd-textarea won't take the height of the container.

## Expected behavior
I would expect that the input field of the sd-textarea has the same height as the container.

## Steps to reproduce
https://jsfiddle.net/f3krvean/1/

## Technical Information
without part-selectors:
grafik

fix with part-selectors:
grafik
grafik

## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant E2E tests (Features, A11y, Bug fixes) are created/updated
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by Vahid1919**
## Description:

The textarea now takes the full height of it's container. Closes #719.
## Definition of Reviewable:

- [x] relevant tickets are linked

### CODE REVIEW

**Comment by karlbaumhauer** [comment]
based on our teams dicussion, pls add a test for this.

**Review by karlbaumhauer — CHANGES_REQUESTED** [review]
based on our teams dicussion, pls add a test for this.

**Comment by coraliefeil** [comment]
Leave review to you @MartaPintoTeixeira

**Comment by Vahid1919** [comment]
@karlbaumhauer Added screenshot test :)

**Comment by MartaPintoTeixeira** [comment]
Please check my comment in Chromatic

**Review by karlbaumhauer — APPROVED** [review]

**Review by MartaPintoTeixeira — APPROVED** [review]

**Pull request merged**
