### PR TITLE
docs: 📚 add privacy statement to storybook [skip chromatic]

### LINKED ISSUE #687: docs: 📚 add privacy statement to storybook
## Description
In order to cover legal regulations, we need a privacy statement page in our storybook.
As an imprint file will follow, a new "legal" chapter in our storybook needs to be created. This ticket only covers the first page ("privacy") in the legal chapter, and contains the following text:

[sds-privacy.md](https://github.com/solid-design-system/solid/files/13953369/sds-privacy.md)

The legal section from [DB](https://db-ui.github.io/elements/?path=/story/20-legal-datenschutzerklaerung--datenschutzerklaerung) is used as structure sample.

## Where to put the documentation
Storybook
## DoR
- [x] Item has business value
- [x] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Migration Guide has been created/updated (if applicable)
- [ ] Relevant stories (Features, A11y) are created/updated
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by azraefendic**
## Description:
Added 'Legal' chapter and 'Privacy Statement' to Storybook.

Closes #687 

## Definition of Reviewable:
*PR notes: Irrelevant elements should be removed.*
- [x] Documentation is created/updated
- [x] relevant tickets are linked
- [x] PR is assigned to project board

### CODE REVIEW

**Comment by mariohamann** [comment]
CleanShot 2024-01-22 at 14 24 43

1. Please "Legal", not "legal.
2. Could you change the order, that "legal" is after components? You can do this by editing this array https://github.com/solid-design-system/solid/blob/docs/add-privacy-statement/packages/components/.storybook/main.cjs#L3-L8 and changing the order of inputs
3. This should be placed here: https://github.com/solid-design-system/solid/tree/docs/add-privacy-statement/packages/components/src/docs

**Review by mariohamann — CHANGES_REQUESTED** [review]
See comment.

**Comment by azraefendic** [comment]
@mariohamann so I tried adjusting the order of inputs array and move the folder into 'docs', but it's not very straightforward and has several issues due to the current logic where we are displaying the entire docs folder at the beginning so we would need more adjustments then to have the legal folder inside but also showcase it separately at the bottom. I feel like this solution is also good where I just adjusted the order but if you feel like we should still change the structure as well maybe we can take a look into it together?

**Review by mariohamann — APPROVED** [review]
The result LGTM!

**Review by karlbaumhauer — APPROVED** [review]

**Pull request merged**
