### PR TITLE
feat: ✨ update tokens

### PR DESCRIPTION
**Pull request by mariohamann**
In addition to the tokens, we have to update button and accordion that it matches the new a11y concept:

- [x] button
- [x] accordion

@coraliefeil @van-nguyen-ht https://github.com/solid-design-system/figma/issues/88 Are the tokens already updated in Figma for the `sd-accordion`?

When I read it correctly, it's updated for the button, but not for the `sd-accordion`. This currently blocks updating the tokens.

### CODE REVIEW

**Comment by karlbaumhauer** [comment]
@coraliefeil / @van-nguyen-ht is this the correct new green? https://www.chromatic.com/test?appId=64469bd84c5ea1ce2dd5d016&id=64c90dbc90030fa1dbafde53

**Comment by van-nguyen-ht** [comment]
@mariohamann @karlbaumhauer 
is this the correct new green? -> yes it is text.accent & fill.accent of hex value #2D9D00

**Review by azraefendic — APPROVED** [review]

**Comment by mariohamann** [comment]
As stated in the inteoduction, first the button tokens have to be updated in the button component before this can be updated.

**Review by yoezlem — APPROVED** [review]

**Comment by coraliefeil** [comment]
For the sd-accordion – figma component – the color tokens are up to date ... layout refresh is handled separately.

https://64469bd84c5ea1ce2dd5d016-bdfamulaiw.chromatic.com/?path=/story/components-sd-button--default&args=variant-attr:cta
-> CTA colors need to be updated according to adjusted tokens

**Comment by mariohamann** [comment]
@coraliefeil There was a bug in our tokens script, which occured after the tokens in the Figma Plugin  had a different order. It's fixed now.

@solid-design-system/development @solid-design-system/design Could you please have a second look, if it's fine now?

**Comment by karlbaumhauer** [comment]
LGTM

**Review by karlbaumhauer — APPROVED** [review]

**Comment by coraliefeil** [comment]
LGTM

**Pull request merged**
