### PR TITLE
chore: update failing tests

### PR DESCRIPTION
**Pull request by smfonseca**
## Description:
This PR address two failing tests in the audio component

## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated

- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

### CODE REVIEW

**Review by Vahid1919 — APPROVED** [review]

**Review by mariohamann — CHANGES_REQUESTED** [review]
We try to avoid external files as we this could lead to CDN issues (we already had that.) Isn't there a local way? I would even prefer base64. :D

**Comment by mariohamann** [comment]
Changed title, as no version bump needed.

**Comment by smfonseca** [comment]
> We try to avoid external files as we this could lead to CDN issues (we already had that.) Isn't there a local way? I would even prefer base64. :D

I've added the audio as base64. We also need to update the sd-video tests since it's using an external source. I will create a ticket for that.

**Review by mariohamann — APPROVED** [review]
So beautiful ugly. :D

**Pull request merged**
