### PR TITLE
ci: turn off dependabot

### LINKED ISSUE #437: ci: 👷 Turn off dependabot
## User Story
As a developer of the Solid Design System, I would like to have dependabot turned off as well as open dependabot PRs closed so that I can have a concise view of all open PRs without interference from a dozen open PRs from dependabot that are failing since dependbot is not full working yet. 

### Suggested Solution
- Set the limit of open PRs on dependabot to 0. 
- Close all open dependabot PRs

## Environment (GitHub Actions or Azure DevOps)
Github

## DoR
- [x] Item has business value
- [ ] Item has been estimated by the team
- [x] Item is clear and well-defined
- [x] Item dependencies have been identified

## DoD
- [ ] Documentation has been created/updated (if applicable)
- [ ] Implementation works successfully on `feature` branch

### PR DESCRIPTION
**Pull request by Vahid1919**
## Description:
Stopped dependabot from carrying out any additional PRs. Closes #437 

## Definition of Reviewable:
*PR notes: Irrelevant elements should be removed.*
- [x] relevant tickets are linked
- [x] PR is assigned to project board

### CODE REVIEW

**Comment by Vahid1919** [comment]
@solid-design-system/development Please Review :)

**Review by azraefendic — APPROVED** [review]

**Comment by mariohamann** [comment]
CleanShot 2023-09-29 at 08 34 24@2x

What is with this stuff? Do we need this, if dependabot is deactivated?

Can't we just revert the commit from some weeks ago, that we resettle this at another point?

**Review by mariohamann — CHANGES_REQUESTED** [review]
See other comment.

**Comment by Vahid1919** [comment]
> CleanShot 2023-09-29 at 08 34 24@2x
> What is with this stuff? Do we need this, if dependabot is deactivated?
> 
> Can't we just revert the commit from some weeks ago, that we resettle this at another point?

@mariohamann We won't need while dependabot is on. 
Reverting the commit is one option, but we could also just disable them for the repository and leave a note on #416 to turn them on after dependabot gets fixed?

**Review by yoezlem — APPROVED** [review]

**Comment by mariohamann** [comment]
What holds you back from making a revert commit and just linking the commit to the issue?

Currently we neither need the actions in the PR nor the Dependabot behaviour. On top we maybe will even switch to Renovate or have to rethink our process, therefore I don't see much value in leaving the stuff in code if might even be completely changed at a later point.

What are your toughts on that? :)

**Comment by Vahid1919** [comment]
> What holds you back from making a revert commit and just linking the commit to the issue?
> 
> Currently we neither need the actions in the PR nor the Dependabot behaviour. On top we maybe will even switch to Renovate or have to rethink our process, therefore I don't see much value in leaving the stuff in code if might even be completely changed at a later point.
> 
> What are your toughts on that? :)

Okay I think in that case a revert makes sense. I didn't consider the possibility of moving to renovate.  I didn't believe it was necessary to revert everything if we are putting it back after a fix (since the changes also includes some documentation). 

But since, that's undecided I'll go ahead and do the revert.

**Review by mariohamann — APPROVED** [review]

**Pull request merged**
