### PR TITLE
feat(PB2B-1085): setupautocomplete versioned [skip chromatic]

### PR DESCRIPTION
**Pull request by rolbr**
## Description:
https://jira.apps.union-investment.de/browse/PB2B-12375

Updates `setupAutocomplete()` to allow **versioned** `sd-1-2-3-input` and `sd-1-2-3-popup` instances to be provided as parameters.

This resolves an issue where `setupAutocomplete()` would create an **unversioned** `sd-popup` internally, preventing teams to use versioned components.

The proposed changes enable teams to use either versioned or unversioned components.

Minor cleanup in stories.

## Definition of Reviewable:
- [x] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated
- [x] Stories (features, a11y) are created/updated
- [x] relevant tickets are linked

### CODE REVIEW

**Comment by mariohamann** [comment]
Thanks for the PR. We totally missed this use case. I'm not sure about the implementation and will have to wrap my head around it. Please don't expect too much until EOW. 🙏🏻

**Comment by rolbr** [comment]
Ahoi! @mariohamann 

Thanks for chipping in. Currently busy adapting / expanding the unit tests.
If you catch me today, I'd be happy to peer and walk you through the changes. I'll then be off for the rest of the week.

**Comment by rolbr** [comment]
@mariohamann 
Buenos! I guess this PR can be closed?

**Comment by mariohamann** [comment]
If you're fine with the other solution, I would be happy about that. 🥹

**Pull request closed without merging**
