### PR TITLE
fix: solid faker seed for paragraphs and sentences

### PR DESCRIPTION
**Pull request by christophsaile**
## Definition of Reviewable:

- [ ] Documentation is created/updated
- [ ] Migration Guide is created/updated
- [ ] E2E tests (features, a11y, bug fixes) are created/updated
- [ ] Stories (features, a11y) are created/updated
- [ ] relevant tickets are linked

### CODE REVIEW

**Comment by christophsaile** [comment]
@solid-design-system/core-development it would be nice if someone could verify that everything is working. I tried different scenarios and all of them looked good but just to be sure :)

**Review by smfonseca — COMMENTED** [review]
I've tested your changes and all seems to be fine, the only request I would have is that we move the script and its tests into an `utilities` folder just to keep everything organized.

**Comment by mariohamann** [comment]
> I've tested your changes and all seems to be fine, the only request I would have is that we move the script and its tests into an `utilities` folder just to keep everything organized.

As this utility is in its own package, I would leave it as is, as it's the `src` of this package.

**Comment by smfonseca** [comment]
I agree with your point @mariohamann but I'm also looking into the future where we may add other utilities and then it can start becoming unorganized. But this is something we can care about when the time arrives. Let's just move forward with the PR.

**Review by smfonseca — APPROVED** [review]

**Pull request merged**
