### PR TITLE
fix: 🤔 added part selector to accordion content slot.

### PR DESCRIPTION
**Pull request by yoezlem**
The requirement: https://github.com/solid-design-system/solid/issues/450

### CODE REVIEW

**Review by karlbaumhauer — APPROVED** [review]

**Comment by Vahid1919** [comment]
@yoezlem I noticed that the animation is no longer smooth after moving the padding to the parent. It disappears before the closing animation making it stutter on my device.

https://github.com/solid-design-system/solid/assets/63849626/3f2b2592-0289-41e1-841e-c4879464113a


 One possible solution I found is to speed up the animation (duration 150 instead of 300) and that masks this behavior. I couldn't find a better solution personally, but would love to hear other ideas.

**Comment by mariohamann** [comment]
Maybe an alternative approach: Could we give the slot a part selector, too?

**Comment by yoezlem** [comment]
I don't know if its clear enough whats the different between those two is:
image

Maybe we could add here content-container or something like that?
image

**Comment by Vahid1919** [comment]
> Good eye, @Vahid1919.
> 
> Maybe an alternative approach: Could we give the slot a part selector, too?
> 
> `part="content__slot"`

@mariohamann That's a better approach. 

I added an offset for the outlines for the Parts story. That's because "content__slot" is not visible there since the parent has an "overflow-hidden". I added the new changes.

**Comment by Vahid1919** [comment]
> I don't know if its clear enough whats the different between those two is
> Maybe we could add here content-container or something like that? 

Yes, I think adding wording like container makes the most sense

**Comment by karlbaumhauer** [comment]
@Vahid1919 / @yoezlem is it on purpose that this is still a draft?

**Comment by Vahid1919** [comment]
@solid-design-system/development Please Review :) 

@van-nguyen-ht I added you as an assignee regarding the UI Reviews :)

**Review by mariohamann — APPROVED** [review]

**Review by azraefendic — APPROVED** [review]

**Pull request merged**
